/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "Tag-2.20-2021-11-24-97-gd2d54c3"
#endif /* AVUTIL_FFVERSION_H */
